#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}🐒 StoneMonkey Startup Script${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Function to print step headers
step() {
  echo ""
  echo -e "${BLUE}==>${NC} ${GREEN}$1${NC}"
}

# Function to print warnings
warn() {
  echo -e "${YELLOW}⚠️  $1${NC}"
}

# Function to print errors
error() {
  echo -e "${RED}❌ $1${NC}"
}

# Function to print success
success() {
  echo -e "${GREEN}✅ $1${NC}"
}

# Function to generate secure random token
generate_token() {
  openssl rand -base64 32
}

# Parse command line arguments
DOCKER_MODE=false
for arg in "$@"; do
  case $arg in
    --docker)
      DOCKER_MODE=true
      shift
      ;;
  esac
done

# Detect if we're in Codespaces
if [ ! -z "$CODESPACES" ]; then
  echo -e "${BLUE}🌐 Detected GitHub Codespaces environment${NC}"
  WORKSPACE_ROOT="/workspaces/$(basename $GITHUB_REPOSITORY 2>/dev/null || echo 'symagenic.com')"

  # Recommend Docker mode for Codespaces
  if [ "$DOCKER_MODE" = false ]; then
    warn "Codespaces detected! For full security integration, consider using:"
    warn "  ./start.sh --docker"
    echo ""
  fi
else
  echo -e "${BLUE}💻 Detected local environment${NC}"
  WORKSPACE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

# Display deployment mode
if [ "$DOCKER_MODE" = true ]; then
  echo -e "${BLUE}🐳 Mode: Full Docker Deployment (ailumina-server + infrastructure)${NC}"
else
  echo -e "${BLUE}💻 Mode: Local Development (local server + Docker infrastructure)${NC}"
fi

STONEMONKEY_ROOT="$WORKSPACE_ROOT/StoneMonkey"
echo -e "${BLUE}📁 StoneMonkey root: $STONEMONKEY_ROOT${NC}"
echo ""

# Change to StoneMonkey directory
cd "$STONEMONKEY_ROOT" || {
  error "Failed to change to StoneMonkey directory"
  exit 1
}

# Step 1: Check/Install Bun
step "Step 1: Checking for Bun runtime..."
if ! command -v bun &> /dev/null; then
  warn "Bun not found, installing..."
  curl -fsSL https://bun.sh/install | bash

  # Source bun environment
  export BUN_INSTALL="$HOME/.bun"
  export PATH="$BUN_INSTALL/bin:$PATH"

  # Also add to bashrc if not already there
  if ! grep -q 'BUN_INSTALL' ~/.bashrc; then
    echo 'export BUN_INSTALL="$HOME/.bun"' >> ~/.bashrc
    echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> ~/.bashrc
  fi

  if command -v bun &> /dev/null; then
    success "Bun installed successfully ($(bun --version))"
  else
    error "Failed to install Bun"
    exit 1
  fi
else
  success "Bun already installed ($(bun --version))"
fi

# Step 2: Install Dependencies
step "Step 2: Installing dependencies..."

echo "📦 Installing root dependencies..."
npm install

echo "📦 Installing shared package..."
cd shared && npm install && cd ..

echo "📦 Installing server dependencies..."
cd server && npm install && cd ..

echo "📦 Installing client dependencies..."
cd client && npm install && cd ..

success "All dependencies installed"

# Step 3: Build Shared Package
step "Step 3: Building shared package..."
(cd "$STONEMONKEY_ROOT/shared" && npm run build)
success "Shared package built"

# Step 4: Check Environment Variables
step "Step 4: Checking environment configuration..."

# Create/update root .env file (used by Docker compose)
if [ ! -f .env ]; then
  echo "Creating .env with secure auto-generated secrets..."

  # Copy from example
  cp .env.example .env

  # Generate secure secrets
  echo "" >> .env
  echo "# Auto-generated secure secrets (generated by start.sh)" >> .env
  echo "NEO4J_PASSWORD=$(generate_token)" >> .env
  echo "REDIS_PASSWORD=$(generate_token)" >> .env
  echo "BEARER_TOKEN=$(generate_token)" >> .env
  echo "EMBEDDING_SERVICE_AUTH_TOKEN=$(generate_token)" >> .env

  # Add API keys from environment if available
  if [ ! -z "$GROQ_API_KEY" ]; then
    sed -i.bak "s|GROQ_API_KEY=.*|GROQ_API_KEY=$GROQ_API_KEY|" .env && rm .env.bak
  fi
  if [ ! -z "$ANTHROPIC_API_KEY" ]; then
    echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> .env
  fi
  if [ ! -z "$OPENAI_API_KEY" ]; then
    echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
  fi

  # Configure for deployment mode
  if [ "$DOCKER_MODE" = true ]; then
    # Docker mode: use container hostnames
    sed -i.bak "s|NEO4J_URI=.*|NEO4J_URI=bolt://neo4j:7687|" .env && rm .env.bak
    sed -i.bak "s|REDIS_HOST=.*|REDIS_HOST=redis|" .env && rm .env.bak
    sed -i.bak "s|QDRANT_URL=.*|QDRANT_URL=http://qdrant:6333|" .env && rm .env.bak
    sed -i.bak "s|EMBEDDING_SERVICE_URL=.*|EMBEDDING_SERVICE_URL=http://embeddings:3007|" .env && rm .env.bak
    sed -i.bak "s|AUTH_ENABLED=.*|AUTH_ENABLED=true|" .env && rm .env.bak

    # Set CORS for Codespaces port forwarding if in Codespaces
    if [ ! -z "$CODESPACES" ]; then
      CODESPACE_NAME=$(echo $CODESPACE_NAME | tr '[:upper:]' '[:lower:]')
      CORS_ORIGIN="https://${CODESPACE_NAME}-8000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
      sed -i.bak "s|CORS_ORIGINS=.*|CORS_ORIGINS=http://localhost:8000,http://localhost:3000,$CORS_ORIGIN|" .env && rm .env.bak
    else
      sed -i.bak "s|CORS_ORIGINS=.*|CORS_ORIGINS=http://localhost:8000,http://localhost:3000|" .env && rm .env.bak
    fi
  fi

  success ".env created with secure auto-generated secrets"
else
  success ".env already exists (preserving your configuration)"
fi

# Check for API keys
if [ -z "$GROQ_API_KEY" ] && [ -z "$ANTHROPIC_API_KEY" ] && [ -z "$OPENAI_API_KEY" ]; then
  warn "No AI provider API key found!"
  warn "Please set one of: GROQ_API_KEY, ANTHROPIC_API_KEY, or OPENAI_API_KEY"
  warn ""
  warn "For Codespaces: Add as a repository secret"
  warn "For local: Add to StoneMonkey/.env"
else
  if [ ! -z "$GROQ_API_KEY" ]; then
    success "Groq API key detected"
  fi
  if [ ! -z "$ANTHROPIC_API_KEY" ]; then
    success "Anthropic API key detected"
  fi
  if [ ! -z "$OPENAI_API_KEY" ]; then
    success "OpenAI API key detected"
  fi
fi

# Step 5: Start Infrastructure
step "Step 5: Starting infrastructure (Docker)..."

# Check if Docker is available
if ! command -v docker &> /dev/null; then
  error "Docker not found! Please install Docker first."
  exit 1
fi

# Check if docker daemon is running
if ! docker info &> /dev/null; then
  error "Docker daemon is not running! Please start Docker."
  exit 1
fi

if [ "$DOCKER_MODE" = true ]; then
  # Docker mode: Build and start all services including ailumina-server
  echo "🐳 Building client for Docker deployment..."
  (cd "$STONEMONKEY_ROOT/client" && npm run build)

  echo "🐳 Starting all Docker containers (full stack)..."
  echo "   - Infrastructure: Neo4j, Redis, Qdrant, Embeddings, Ollama"
  echo "   - MCP Servers: ai-memory, ai-mesh, ai-recall, ailumina-bridge"
  echo "   - AIlumina Server: ailumina-server (with embedded UI)"

  # Build ailumina-server image with embedded client
  docker-compose build ailumina-server

  # Start all containers
  docker-compose up -d

  echo "⏳ Waiting for all services to be ready (30 seconds)..."
  sleep 30

  # Check container status
  echo ""
  echo "📊 Service status:"
  docker-compose ps

  # Count running containers (expect 9: 5 infrastructure + 4 MCP)
  RUNNING_COUNT=$(docker-compose ps --format json 2>/dev/null | grep -c '"State":"running"' || echo "0")

  if [ "$RUNNING_COUNT" -ge 9 ]; then
    success "All services running in Docker"
  else
    warn "Some services may still be starting (found $RUNNING_COUNT running)"
    warn "This is normal on first run - containers are building"
    warn "Check with: docker-compose ps"
  fi
else
  # Local mode: Start infrastructure only, local server later
  echo "🐳 Starting Docker containers (infrastructure only)..."
  echo "   - Infrastructure: Neo4j, Redis, Qdrant, Embeddings, Ollama"
  echo "   - MCP Servers: ai-memory, ai-mesh, ai-recall, ailumina-bridge"
  echo "   - AIlumina Server: Will run locally with Bun"

  # Start infrastructure and MCP services (exclude ailumina-server)
  docker-compose up -d neo4j redis qdrant embedding-service ollama \
    ai-memory-mcp ai-mesh-mcp ai-recall-mcp ailumina-bridge-mcp

  echo "⏳ Waiting for infrastructure to be ready (20 seconds)..."
  sleep 20

  # Check container status
  echo ""
  echo "📊 Infrastructure status:"
  docker-compose ps

  # Count healthy containers (4 infrastructure + 4 MCP = 8 total)
  HEALTHY_COUNT=$(docker-compose ps --format json 2>/dev/null | grep -c '"State":"running"' || echo "0")

  if [ "$HEALTHY_COUNT" -ge 8 ]; then
    success "All infrastructure and MCP services running"
  elif [ "$HEALTHY_COUNT" -ge 4 ]; then
    warn "Infrastructure running, but some MCP services may still be starting"
    warn "MCP servers may need additional time to build on first run"
    warn "Check with: docker-compose ps"
  else
    warn "Some services may not be ready yet"
    warn "Check with: docker-compose ps"
  fi

  # Step 6: Build Client
  step "Step 6: Building client..."
  (cd "$STONEMONKEY_ROOT/client" && npm run build)
  success "Client built"

  # Step 7: Deploy Client to Server
  step "Step 7: Deploying client to server..."
  (cd "$STONEMONKEY_ROOT" && npm run deploy:client)
  success "Client deployed to server/dist/client"
fi

# Step 8: Final Summary
echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✅ StoneMonkey is ready!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

if [ "$DOCKER_MODE" = true ]; then
  # Docker mode summary
  echo -e "${BLUE}🐳 Docker Mode - All services running in containers${NC}"
  echo ""
  echo -e "${BLUE}📍 Access URLs:${NC}"
  echo ""

  if [ ! -z "$CODESPACES" ]; then
    # Codespaces: Show forwarded URLs
    CODESPACE_NAME=$(echo $CODESPACE_NAME | tr '[:upper:]' '[:lower:]')
    UI_URL="https://${CODESPACE_NAME}-8000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
    echo -e "  • AIlumina UI:        ${GREEN}${UI_URL}${NC}"
    echo -e "  • Neo4j Browser:      Check Codespaces ports tab for port 7474"
    echo -e "  • Qdrant Dashboard:   Check Codespaces ports tab for port 6333"
  else
    # Local Docker: Show localhost URLs
    echo -e "  • AIlumina UI:        ${GREEN}http://localhost:8000${NC}"
    echo -e "  • Neo4j Browser:      ${GREEN}http://localhost:7474${NC}"
    echo -e "  • Qdrant Dashboard:   ${GREEN}http://localhost:6333/dashboard${NC}"
  fi

  echo ""
  echo -e "${BLUE}🔧 MCP Servers (Consciousness Tools):${NC}"
  echo ""
  echo -e "  • All MCP servers running in Docker containers"
  echo -e "  • Check status: ${YELLOW}docker-compose ps${NC}"
  echo ""
  echo -e "${BLUE}🛠️  Useful commands:${NC}"
  echo ""
  echo -e "  ${YELLOW}docker-compose ps${NC}                    Check all services status"
  echo -e "  ${YELLOW}docker-compose logs -f ailumina-server${NC} View server logs"
  echo -e "  ${YELLOW}docker-compose logs -f${NC}                View all logs"
  echo -e "  ${YELLOW}docker-compose down${NC}                   Stop all services"
  echo -e "  ${YELLOW}docker-compose restart ailumina-server${NC} Restart server"
else
  # Local mode summary
  echo -e "${BLUE}💻 Local Mode - Server ready to start${NC}"
  echo ""
  echo -e "${BLUE}🚀 To start the server:${NC}"
  echo ""
  echo -e "  ${YELLOW}cd server && bun src/http-server/index.ts${NC}"
  echo ""
  echo -e "${BLUE}📍 Access URLs:${NC}"
  echo ""
  echo -e "  • AIlumina UI:        ${GREEN}http://localhost:8000${NC}"
  echo -e "  • Neo4j Browser:      ${GREEN}http://localhost:7474${NC}"
  echo -e "  • Qdrant Dashboard:   ${GREEN}http://localhost:6333/dashboard${NC}"
  echo ""
  echo -e "${BLUE}🔧 MCP Servers (Consciousness Tools):${NC}"
  echo ""
  echo -e "  • AI Memory MCP:      ${GREEN}http://localhost:3001${NC} (Neo4j graph)"
  echo -e "  • AI Mesh MCP:        ${GREEN}http://localhost:3002${NC} (Redis pub/sub)"
  echo -e "  • AI Recall MCP:      ${GREEN}http://localhost:3003${NC} (Qdrant search)"
  echo -e "  • Ailumina Bridge:    ${GREEN}http://localhost:3004${NC} (Agent bridge)"
  echo ""
  echo -e "${BLUE}🛠️  Useful commands:${NC}"
  echo ""
  echo -e "  ${YELLOW}docker-compose ps${NC}              Check infrastructure status"
  echo -e "  ${YELLOW}docker-compose logs -f${NC}         View infrastructure logs"
  echo -e "  ${YELLOW}docker-compose down${NC}            Stop infrastructure"
  echo -e "  ${YELLOW}docker-compose restart${NC}         Restart infrastructure"
fi

echo ""
echo -e "${BLUE}========================================${NC}"
echo ""

# Optional: Auto-start server (local mode only)
if [ "$DOCKER_MODE" = false ]; then
  read -p "Would you like to start the server now? (y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    success "Starting server..."
    cd server && bun src/http-server/index.ts
  fi
fi
